# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.3&openapi/v0.0.39&openapi/dbv0.0.39&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0039_step import V0039Step

class TestV0039Step(unittest.TestCase):
    """V0039Step unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0039Step:
        """Test V0039Step
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0039Step`
        """
        model = V0039Step()
        if include_optional:
            return V0039Step(
                time = openapi_client.models.v0_0_39_step_time.v0_0_39_step_time(
                    elapsed = 56, 
                    end = 56, 
                    start = 56, 
                    suspended = 56, 
                    system = openapi_client.models.v0_0_39_step_time_system.v0_0_39_step_time_system(
                        seconds = 56, 
                        microseconds = 56, ), 
                    total = openapi_client.models.v0_0_39_step_time_system.v0_0_39_step_time_system(
                        seconds = 56, 
                        microseconds = 56, ), 
                    user = , ),
                exit_code = openapi_client.models.v0/0/39_job_exit_code.v0.0.39_job_exit_code(
                    status = '', 
                    return_code = 56, 
                    signal = openapi_client.models.v0_0_39_job_exit_code_signal.v0_0_39_job_exit_code_signal(
                        signal_id = 56, 
                        name = '', ), ),
                nodes = openapi_client.models.v0_0_39_step_nodes.v0_0_39_step_nodes(
                    count = 56, 
                    range = '', 
                    list = [
                        ''
                        ], ),
                tasks = openapi_client.models.v0_0_39_step_tasks.v0_0_39_step_tasks(
                    count = 56, ),
                pid = '',
                cpu = openapi_client.models.v0_0_39_step_cpu.v0_0_39_step_CPU(
                    requested_frequency = openapi_client.models.v0_0_39_step_cpu_requested_frequency.v0_0_39_step_CPU_requested_frequency(
                        min = openapi_client.models.v0/0/39_uint32_no_val.v0.0.39_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        max = openapi_client.models.v0/0/39_uint32_no_val.v0.0.39_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), ), 
                    governor = '', ),
                kill_request_user = '',
                state = '',
                statistics = openapi_client.models.v0_0_39_step_statistics.v0_0_39_step_statistics(
                    cpu = openapi_client.models.v0_0_39_step_statistics_cpu.v0_0_39_step_statistics_CPU(
                        actual_frequency = 56, ), 
                    energy = openapi_client.models.v0_0_39_step_statistics_energy.v0_0_39_step_statistics_energy(
                        consumed = openapi_client.models.v0/0/39_uint64_no_val.v0.0.39_uint64_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), ), ),
                step = openapi_client.models.v0_0_39_step_step.v0_0_39_step_step(
                    id = openapi_client.models.v0/0/39_slurm_step_id.v0.0.39_slurm_step_id(
                        job_id = 56, 
                        step_het_component = 56, 
                        step_id = '', ), 
                    name = '', ),
                task = openapi_client.models.v0_0_39_step_task.v0_0_39_step_task(
                    distribution = '', ),
                tres = openapi_client.models.v0_0_39_step_tres.v0_0_39_step_tres(
                    requested = openapi_client.models.v0_0_39_step_tres_requested.v0_0_39_step_tres_requested(
                        max = [
                            openapi_client.models.v0/0/39_tres.v0.0.39_tres(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], 
                        min = [
                            openapi_client.models.v0/0/39_tres.v0.0.39_tres(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], 
                        average = [
                            
                            ], 
                        total = [
                            
                            ], ), 
                    consumed = openapi_client.models.v0_0_39_step_tres_consumed.v0_0_39_step_tres_consumed(), 
                    allocated = , )
            )
        else:
            return V0039Step(
        )
        """

    def testV0039Step(self):
        """Test V0039Step"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
