# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.3&openapi/v0.0.39&openapi/dbv0.0.39&openapi/slurmdbd&openapi/slurmctld
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0039_rollup_stats_inner import V0039RollupStatsInner

class TestV0039RollupStatsInner(unittest.TestCase):
    """V0039RollupStatsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0039RollupStatsInner:
        """Test V0039RollupStatsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0039RollupStatsInner`
        """
        model = V0039RollupStatsInner()
        if include_optional:
            return V0039RollupStatsInner(
                type = 'internal',
                last_run = 56,
                max_cycle = 56,
                total_time = 56,
                total_cycles = 56,
                mean_cycles = 56
            )
        else:
            return V0039RollupStatsInner(
        )
        """

    def testV0039RollupStatsInner(self):
        """Test V0039RollupStatsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
